version: '3.8'
services:
  resume:
    build: .
    restart: unless-stopped
    networks:
      - server
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.resume.rule=HOST(`resume.timohermans.nl`)'
      - 'traefik.http.services.resume.loadbalancer.server.port=80'

networks:
  server:
    external: true